using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Watson.Core.Entities;

namespace Watson.Application.Services
{
	public static class PdfService
	{
		public static async Task<PdfFileInfo> GenerateSamplePdf(IEnumerable<Note> notes)
		{
			try
			{
				Document document = Document.Create(container =>
				{
					container.Page(page =>
					{
						page.Size(PageSizes.A4);
						page.Margin(2, Unit.Centimetre);
						page.PageColor(Colors.White);
						page.DefaultTextStyle(x => x.FontSize(11).FontFamily("Arial", "Calibri", "Tahoma"));

						page.Content().Column(column =>
						{
							foreach (var note in notes)
							{
								column.Item().PaddingBottom(10).Column(noteColumn =>
								{
									noteColumn.Item().Text(note.Name).FontSize(14).Bold();
									noteColumn.Item().Text(note.Description).FontSize(12);
									noteColumn.Item().Text($"Transform: {note.ObjectMetadata.Position[0]}, {note.ObjectMetadata.Position[1]}, {note.ObjectMetadata.Position[2]}").FontSize(10);
								});
							}
						});

						page.Footer()
							.AlignCenter()
							.Text(x =>
							{
								x.Span("THIS IS GENERATED BY WATSON").FontSize(9);
							});
					});
				});

				byte[] pdfBytes = document.GeneratePdf();

				return new PdfFileInfo()
				{
					ByteArray = pdfBytes,
					FileName = "sporenmatrix.pdf",
					MimeType = "application/pdf"
				};
			}
			catch (Exception ex)
			{
				throw ex;
			}

		}
	}
}
